### ISSUE TITLE
Migration from ttnews (fal ready) to news failed

### ISSUE THREAD

**Issue by alat54** [fsaris/news_ttnewsimport#18]
Hi, 

Images are not migrated.
Is there any order to follow for migrate tt_news (with dam) to news (with fal)?
I test ttnews dam -> ttnews fal (and it's ok, images are here)
ttnews fal -> news with the importer and images are not linked in news records :(

thanks

**Comment by alat54** [comment]
I found the tips : i have to migrate ttnews dam to news fal with the importer before migrate all files from dam to fal...
it makes me crazy ^^

**Comment by metrgonzoo** [comment]
Hi,

I'm using Typo3 6.2.11
Ext:news 3.0.1
Ext: news_ttnewsimport 1.0.1

I have the same problem, 

"tt_news record" to "tx_news_domain_model_news" is OK
"tt_news_cat" to "sys_category" is OK

But all media is lost, can you explain me what is your way, to import the media? Do you use any other extension to convert the DAM to FAL?

Thx

**Comment by frans-beech-it** [comment]
Hi,

requirements for the migration to work is:
 - tx_dam table is present
 - tx_dam_mm_ref table is present
 - tt_news table is present
 - ext:news is setup and works (best way to test is creating a test news item with image and check if it shows on front-end)
 - ext:news is configured to use FAL (see extension manager for ext:news settings)
 - all images need to be availeble on there original place as they where when using DAM

The news importer will move the images when needed to the configured import folder if they aren't already in your file storage.

gr. Frans

**Comment by metrgonzoo** [comment]
Hi, Thx for your answer. 
I'm trying your solution but I have some problems.

In my new install of Typo3 6.2.11, I have installed the following EXT :

- tt_news 3.6.0
- news 3.1.0
- tt_news importer 1.0.1

In the configuration of news extension, I have :

Use FAL relations instead of news media elements [records.useFal] => Yes
Show importer [backend modules.showImporter] => True
In which folder should the importer save files/images [backend modules.resourceFolderImporter] => I set for exemple "/fileadmin/images/news"

1 error : when I go to the News Import module, I have always the same error message => "The configuration for the import is incomplete! 
The directory defined in the setting "resourceFolderImporter" does not exist!"

But, I'm sure that the folder exist with any permissions!

2. I have a new record with media (ex: picture saved as /upload/pics folder)

If this folder exist, I have an popup error during the import action, but when the folder isn't exist, the import make no error, but the media file is not recovered.

Do you know where is my error? No other extension is required?

Thank you

**Comment by alat54** [comment]
n which folder should the importer save files/images [backend modules.resourceFolderImporter] => I set for exemple "/fileadmin/images/news" ==> this link is relative to fileadmin so try :
"images/news"

the folder as to be created by ftp or BO before launch importer

**Comment by frans-beech-it** [comment]
The folder should be set relative to your filestorage.

So if you have a folder ``fileadmin/images/news`` the folder you set in the extension configuration is ``images/news``. Asuming you have a default install where your file storage ``uid = 1`` used folder ``fileadmin``.

The folder ``images/news`` needs to be visible/writeable in the BE filelist. Easiest way to create the folder is also using the BE filelist. 

gr. Frans
