### ISSUE TITLE
Extension fails on importing translated records

### ISSUE THREAD

**Issue by topsnet-holgerd** [fsaris/news_ttnewsimport#48]
The translated record is implemented twice in the tx_news_domain_model_news:
first record is with uid of original not translated record, but with translated content, sys_language_uid = 1 and l10n_parent of itself but lacking t3_origuid,
second is the translated record (correct uid, sys_language_uid, l10n_parent, and contentfields), but with lacking t3_origuid as well.
So nothing of these items will display in frontend or backend

**Comment by franzkugelmann** [comment]
If you experience the same issue, have a look at your old tt_news table. If it is InnoDB, change it to MyISAM and try again.
Just could definitely confirm that this makes the difference on our servers between successful run and failed run with exactly the issues described above.
My guess why InnoDB might be the problem (without checking the code to find the exact reason):
MyISAM does block the whole table on every write, InnoDB does not. I wonder why tt_news needs to be MyISAM though, since it should only be read-accessed.

**Comment by topsnet-holgerd** [comment]
Dear Franz,
thanks a lot for replying. At the Moment I'm not needing the feature. As soon as an import of translated tt_news content will be managed, I'll try to make it with MyISAM. Best, Holger

**Comment by franzkugelmann** [comment]
also see https://github.com/georgringer/news/issues/796
